### ISSUE TITLE
Pluto.js:29963 ReferenceError: swed is not defined

### ISSUE THREAD

**Issue by damirmur** [rubyfmzk/Pluto#1]
Hello Ruby.
Thank you very much for your work.
Gives errors in the console.
Don't tell me what to do with them.
If you do not plan to support this project, you can indicate other sources if you did not do it yourself.

Pluto.js:29963 ReferenceError: swed is not defined
    at SwissEph.app_pos_rest (Pluto.js:32795:7)
    at SwissEph.app_pos_etc_moon (Pluto.js:33785:20)
    at SwissEph.swecalc (Pluto.js:31716:24)
    at SwissEph._calc (Pluto.js:29914:35)
    at SwissEph.swe_calc (Pluto.js:29813:18)
    at SwissEph.swe_calc_ut (Pluto.js:29770:19)
    at Swecl.swe_lun_eclipse_how (Pluto.js:27417:17)
    at Swecl.swe_lun_eclipse_when_loc (Pluto.js:27891:30)
    at SwissEph.swe_lun_eclipse_when_loc (Pluto.js:31244:20)
    at calc (index.js:103:19)

**Comment by damirmur** [comment]
Found and corrected a bug.
27557,32795,32801 line add this.
